In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("/home/jose/Jupyter_Notebooks/Youtube/Pandas/Data/Data.csv" ,encoding = "ISO-8859-1")

In [5]:
#Informacion del archivo
filas=len(df.index)
filas

46652

In [8]:
#informacion del dataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 46651 entries, 0 to 46650
Data columns (total 54 columns):
ATP           46651 non-null int64
Location      46651 non-null object
Tournament    46651 non-null object
Date          46651 non-null object
Series        46651 non-null object
Court         46651 non-null object
Surface       46651 non-null object
Round         46651 non-null object
Best of       46651 non-null int64
Winner        46651 non-null object
Loser         46651 non-null object
WRank         46636 non-null object
LRank         46580 non-null object
W1            46422 non-null float64
L1            46422 non-null float64
W2            45961 non-null float64
L2            45962 non-null float64
W3            21364 non-null float64
L3            21364 non-null float64
W4            4226 non-null float64
L4            4226 non-null float64
W5            1617 non-null float64
L5            1617 non-null float64
Wsets         46461 non-null float64
Lsets         46461 non-null float64
Comment       46651 non-null object
CBW           17507 non-null float64
CBL           17507 non-null float64
GBW           5055 non-null float64
GBL           5055 non-null float64
IWW           13358 non-null float64
IWL           13358 non-null float64
SBW           5424 non-null float64
SBL           5424 non-null float64
B365W         38018 non-null float64
B365L         38041 non-null float64
B&WW          1097 non-null float64
B&WL          1097 non-null float64
EXW           33798 non-null float64
EXL           33803 non-null float64
PSW           31728 non-null float64
PSL           31728 non-null float64
WPts          30447 non-null float64
LPts          30395 non-null float64
UBW           10672 non-null float64
UBL           10672 non-null float64
LBW           23229 non-null float64
LBL           23238 non-null float64
SJW           15572 non-null float64
SJL           15579 non-null float64
MaxW          17103 non-null float64
MaxL          17103 non-null float64
AvgW          17103 non-null float64
AvgL          17103 non-null float64
dtypes: float64(40), int64(2), object(12)
memory usage: 19.6+ MB

In [6]:
#ultimas fila
df.tail(5)

,ATP,Location,Tournament,Date,Series,Court,Surface,Round,Best of,Winner,...,UBW,UBL,LBW,LBL,SJW,SJL,MaxW,MaxL,AvgW,AvgL
46647,54,St. Petersburg,St. Petersburg Open,23/09/2016,ATP250,Indoor,Hard,Quarterfinals,3,Zverev A.,...,NaN,NaN,1.57,2.38,NaN,NaN,1.66,2.45,1.60,2.30
46648,54,St. Petersburg,St. Petersburg Open,23/09/2016,ATP250,Indoor,Hard,Quarterfinals,3,Wawrinka S.,...,NaN,NaN,1.22,4.33,NaN,NaN,1.24,4.91,1.21,4.34
46649,54,St. Petersburg,St. Petersburg Open,24/09/2016,ATP250,Indoor,Hard,Semifinals,3,Zverev A.,...,NaN,NaN,2.38,1.57,NaN,NaN,3.12,1.57,2.68,1.46
46650,54,St. Petersburg,St. Petersburg Open,24/09/2016,ATP250,Indoor,Hard,Semifinals,3,Wawrinka S.,...,NaN,NaN,1.33,3.40,NaN,NaN,1.41,3.80,1.31,3.40
46651,54,St. Petersburg,St. Petersburg Open,25/09/2016,ATP250,Indoor,Hard,The Final,3,Zverev A.,...,NaN,NaN,3.30,1.33,NaN,NaN,3.58,1.36,3.36,1.31

In [7]:
#Eliminar la ultima fila
#drop quitar eliminar
#filas menos-1 por que el cero cuenta
#inplace =True para que se lleve a acabo
df.drop(df.index[[filas-1]],inplace=True)
df.tail(5)

,ATP,Location,Tournament,Date,Series,Court,Surface,Round,Best of,Winner,...,UBW,UBL,LBW,LBL,SJW,SJL,MaxW,MaxL,AvgW,AvgL
46646,54,St. Petersburg,St. Petersburg Open,23/09/2016,ATP250,Indoor,Hard,Quarterfinals,3,Bautista Agut R.,...,NaN,NaN,1.36,3.25,NaN,NaN,1.40,3.45,1.36,3.11
46647,54,St. Petersburg,St. Petersburg Open,23/09/2016,ATP250,Indoor,Hard,Quarterfinals,3,Zverev A.,...,NaN,NaN,1.57,2.38,NaN,NaN,1.66,2.45,1.60,2.30
46648,54,St. Petersburg,St. Petersburg Open,23/09/2016,ATP250,Indoor,Hard,Quarterfinals,3,Wawrinka S.,...,NaN,NaN,1.22,4.33,NaN,NaN,1.24,4.91,1.21,4.34
46649,54,St. Petersburg,St. Petersburg Open,24/09/2016,ATP250,Indoor,Hard,Semifinals,3,Zverev A.,...,NaN,NaN,2.38,1.57,NaN,NaN,3.12,1.57,2.68,1.46
46650,54,St. Petersburg,St. Petersburg Open,24/09/2016,ATP250,Indoor,Hard,Semifinals,3,Wawrinka S.,...,NaN,NaN,1.33,3.40,NaN,NaN,1.41,3.80,1.31,3.40