In [2]:
#Ejercicio de busqueda de alojamiento en Airbnb 
"""
Supongamos que somos un agente de Airbnb localizado en lisboa, y tenemos que atender peticiones 
de varios clientes.  Tenemos un archivo llamado airbnb.csv localizado en la carpeta data 
donde tenemos toda la imformacion de datos alojados en Airbnb Lisboa
"""
import pandas as pd
airbnb=pd.read_csv("/home/jose/data2/airbnb.csv")

In [3]:
airbnb.head()

,room_id,host_id,room_type,neighborhood,reviews,overall_satisfaction,accommodates,bedrooms,price
0,6499,14455,Entire home/apt,Belém,8,5.0,2,1.0,57.0
1,17031,66015,Entire home/apt,Alvalade,0,0.0,2,1.0,46.0
2,25659,107347,Entire home/apt,Santa Maria Maior,63,5.0,3,1.0,69.0
3,29248,125768,Entire home/apt,Santa Maria Maior,225,4.5,4,1.0,58.0
4,29396,126415,Entire home/apt,Santa Maria Maior,132,5.0,4,1.0,67.0

In [ ]:
 """
 En concreto el dataset tiene las siguientes variables:
 - room_id:el identificador de la propiedad
 - host_id:el identificador del dueño de la propiedad
 - room_type:tipo de propiedad
 - neighborhood: el barrio de Lisboa
 - reviews: El numero de opiniones
 - overall_satisfaction: Puntuacion media del apartamento
 - accommodates: El numero de personas que se pueden alojar en la propiedad
 - bedrooms: El numero de habitaciones
 - price: El precio (en euros) por noche
 """

In [ ]:
"""
CASO 1
Alicia va ir de viaje a Lisboa durante una semana con su marido 
y sus dos hijos. Esta buscando un apartamento con habitaciones 
separadas para sus padres e hijos. No les importan el precio
, simplemente quieren tener una experiencia agradable. Esto significa
que solo aceptan lugares con mas de 10 criticas (reviews) con una 
una puntuacion (overall_satisfaction) mayor de 4. Cuando seleccionamos
habitaciones para alicia tenemos que asegurarnos de peor a amejor puntuacion.
Para aquellas habilaciones que tienen la misma puntuacion mostrar la 
que tiene la mayor numero de criticas,mostrar tres alternativas
"""

In [5]:
#Forma uno, con el metodo query
seleccion_alicia=airbnb.query("reviews>10 & overall_satisfaction>4 & bedrooms>=2")
seleccion_alicia.head()

,room_id,host_id,room_type,neighborhood,reviews,overall_satisfaction,accommodates,bedrooms,price
5,29720,128075,Entire home/apt,Estrela,14,5.0,16,9.0,1154.0
12,34977,146695,Entire home/apt,Santa Maria Maior,54,4.5,6,2.0,60.0
14,42172,184400,Entire home/apt,Santa Maria Maior,45,4.5,6,2.0,138.0
16,44043,192830,Entire home/apt,Santa Maria Maior,316,5.0,7,3.0,80.0
22,57850,276092,Entire home/apt,Estrela,52,4.5,3,2.0,70.0

In [7]:
#Forma 2
seleccion_alicia=airbnb[(airbnb.reviews>10) &(airbnb.overall_satisfaction>4)&(airbnb.bedrooms>=2) ]
seleccion_alicia.head()

,room_id,host_id,room_type,neighborhood,reviews,overall_satisfaction,accommodates,bedrooms,price
5,29720,128075,Entire home/apt,Estrela,14,5.0,16,9.0,1154.0
12,34977,146695,Entire home/apt,Santa Maria Maior,54,4.5,6,2.0,60.0
14,42172,184400,Entire home/apt,Santa Maria Maior,45,4.5,6,2.0,138.0
16,44043,192830,Entire home/apt,Santa Maria Maior,316,5.0,7,3.0,80.0
22,57850,276092,Entire home/apt,Estrela,52,4.5,3,2.0,70.0

In [9]:
#Podemos ordenar  la seleccion, primero por la puntuacion y luego por la critica de forma acendente
seleccion_alicia.sort_values(by=["overall_satisfaction","reviews"],ascending=False)

,room_id,host_id,room_type,neighborhood,reviews,overall_satisfaction,accommodates,bedrooms,price
120,176153,842219,Entire home/apt,Misericórdia,438,5.0,4,2.0,102.0
16,44043,192830,Entire home/apt,Santa Maria Maior,316,5.0,7,3.0,80.0
140,202150,989393,Entire home/apt,Santa Maria Maior,274,5.0,4,2.0,62.0
2899,4132059,20604318,Entire home/apt,Misericórdia,273,5.0,6,3.0,48.0
688,785650,4141894,Entire home/apt,Santa Maria Maior,266,5.0,5,3.0,133.0
388,496195,647439,Entire home/apt,Santa Maria Maior,259,5.0,4,2.0,52.0
30,77466,415066,Entire home/apt,Misericórdia,255,5.0,5,2.0,80.0
131,187442,901710,Entire home/apt,Santa Maria Maior,244,5.0,4,2.0,79.0
868,984260,4434549,Entire home/apt,Misericórdia,240,5.0,5,3.0,52.0
804,898363,4794066,Entire home/apt,Santa Maria Maior,236,5.0,6,2.0,58.0
2989,4346065,11997804,Entire home/apt,São Vicente,223,5.0,6,2.0,58.0
382,491368,2381723,Entire home/apt,Arroios,214,5.0,9,4.0,85.0
2286,3121788,4043364,Entire home/apt,Misericórdia,209,5.0,4,2.0,78.0
548,656122,3303813,Entire home/apt,Santa Maria Maior,206,5.0,4,2.0,64.0
1662,2393974,8657639,Entire home/apt,Santa Maria Maior,206,5.0,6,3.0,109.0
1144,1368336,7421918,Entire home/apt,Misericórdia,204,5.0,6,2.0,85.0
656,756329,2496172,Entire home/apt,Misericórdia,203,5.0,6,2.0,93.0
1519,2042416,387186,Entire home/apt,Santa Maria Maior,202,5.0,4,2.0,83.0
838,942922,3676955,Entire home/apt,Misericórdia,201,5.0,7,3.0,138.0
863,976954,4511947,Entire home/apt,Santa Maria Maior,201,5.0,5,2.0,115.0
436,543783,901710,Entire home/apt,Santa Maria Maior,198,5.0,4,2.0,57.0
1059,1235479,6735553,Entire home/apt,Arroios,197,5.0,6,2.0,163.0
1204,1455723,822877,Entire home/apt,Santa Maria Maior,187,5.0,4,2.0,79.0
387,495237,2446180,Entire home/apt,São Vicente,180,5.0,6,2.0,93.0
3997,6259702,21980829,Entire home/apt,Santa Maria Maior,180,5.0,5,2.0,102.0
1291,1580377,8407039,Entire home/apt,Misericórdia,178,5.0,6,2.0,69.0
2346,3196604,10487625,Entire home/apt,Misericórdia,178,5.0,6,3.0,50.0
2428,3339588,16857202,Entire home/apt,São Vicente,174,5.0,8,3.0,75.0
1678,2443900,12094734,Private room,Misericórdia,172,5.0,4,2.0,52.0
1930,2917966,14847119,Entire home/apt,Santo António,172,5.0,6,3.0,69.0
...,...,...,...,...,...,...,...,...,...
10694,17034556,37758551,Entire home/apt,Misericórdia,12,4.5,6,3.0,104.0
10706,17051610,76127721,Entire home/apt,Santa Maria Maior,12,4.5,6,2.0,66.0
11013,17445688,118074004,Entire home/apt,Parque das Nações,12,4.5,5,2.0,52.0
794,888605,2803281,Entire home/apt,Arroios,11,4.5,10,4.0,197.0
825,922645,405842,Entire home/apt,Campolide,11,4.5,4,3.0,58.0
2439,3368932,7247574,Entire home/apt,Misericórdia,11,4.5,8,5.0,231.0
3120,4656661,16521620,Entire home/apt,Campo de Ourique,11,4.5,5,2.0,93.0
3307,5049705,26070945,Entire home/apt,Santo António,11,4.5,6,2.0,57.0
3787,5910669,2372087,Entire home/apt,Arroios,11,4.5,10,4.0,173.0
4464,6907847,17883136,Entire home/apt,Santa Maria Maior,11,4.5,6,2.0,93.0
6333,11145976,17733765,Entire home/apt,Misericórdia,11,4.5,6,2.0,173.0
6335,11151531,57983410,Entire home/apt,São Vicente,11,4.5,6,2.0,106.0
6360,11180081,3953109,Entire home/apt,São Vicente,11,4.5,5,2.0,56.0
6501,11487342,46207193,Entire home/apt,Areeiro,11,4.5,6,2.0,58.0
7014,12246909,63901395,Entire home/apt,Santo António,11,4.5,5,3.0,78.0
7253,12722152,56344244,Entire home/apt,Santa Maria Maior,11,4.5,5,2.0,89.0
7935,13571928,13667856,Entire home/apt,Arroios,11,4.5,6,4.0,88.0
8202,13864327,181902,Entire home/apt,Santa Maria Maior,11,4.5,8,3.0,99.0
8408,14085544,34827624,Entire home/apt,São Vicente,11,4.5,4,2.0,87.0
8514,14192247,6604033,Entire home/apt,Estrela,11,4.5,5,2.0,58.0
8713,14437047,624278,Entire home/apt,Arroios,11,4.5,6,3.0,138.0
8736,14469001,14539928,Entire home/apt,Santo António,11,4.5,5,2.0,84.0
8969,14801814,4141894,Entire home/apt,Santa Maria Maior,11,4.5,5,2.0,104.0
9038,14893514,39465095,Entire home/apt,São Vicente,11,4.5,4,2.0,52.0
9735,15809871,11821479,Entire home/apt,Santo António,11,4.5,7,3.0,69.0
9809,15913748,506703,Entire home/apt,Beato,11,4.5,4,2.0,46.0
9872,16010129,3953109,Entire home/apt,Santo António,11,4.5,4,2.0,84.0
10302,16542149,108850010,Private room,Areeiro,11,4.5,2,2.0,37.0
10671,17008040,48501406,Entire home/apt,Arroios,11,4.5,5,2.0,58.0
11586,17974974,123450353,Entire home/apt,Misericórdia,11,4.5,6,2.0,75.0

In [10]:
#Mostramos los primeros 3 valores
seleccion_alicia.head(3)

,room_id,host_id,room_type,neighborhood,reviews,overall_satisfaction,accommodates,bedrooms,price
5,29720,128075,Entire home/apt,Estrela,14,5.0,16,9.0,1154.0
12,34977,146695,Entire home/apt,Santa Maria Maior,54,4.5,6,2.0,60.0
14,42172,184400,Entire home/apt,Santa Maria Maior,45,4.5,6,2.0,138.0

In [ ]:
"""
CASO 2
Roberto es un casero que tiene una casa en Airbnb. De vez en cuando nos llama preguntando
sobre cuales son las criticas de su alojamiento. Hoy esta particularmente enfadado, ya que su
hermana Clara ha puesto su casa en Airbnb y Roberto quiere asegurarse que su casa tiene mas 
criticas que la de Clara. Tenemos que crear un dataFrame con las propiedades de ambos. Las
id de las propiedades (room_id) de Roberto y Clara son 97503 Y 90387 respectivamente. Finalmente 
guardamos este data frame como un esxel llamado robero.xls
"""

In [12]:
#Primero del data frame  airbnb filtramos la columna room_id y los elemnto de las columnas con el metodo
#isin los elementos  97503 y 90387
roberto=airbnb[airbnb.room_id.isin([97503,90387])]
roberto

,room_id,host_id,room_type,neighborhood,reviews,overall_satisfaction,accommodates,bedrooms,price
41,90387,490050,Private room,Santo António,204,5.0,2,1.0,46.0
48,97503,515924,Private room,Santo António,39,4.0,2,1.0,26.0

In [14]:
roberto.to_excel("roberto.xls",index=False)

In [16]:
roberto=pd.read_excel("roberto.xls")
roberto

,room_id,host_id,room_type,neighborhood,reviews,overall_satisfaction,accommodates,bedrooms,price
0,90387,490050,Private room,Santo António,204,5,2,1,46
1,97503,515924,Private room,Santo António,39,4,2,1,26

In [ ]:
"""
CASO 3
Diana va a Lisboa a pasar 3 noches y quiere conocer a gente nueva. Tiene un presupuesto de
50 euros para su alojamiento. Debemos buscarle las 10 propiedades mas baratas, dandole
preferencia a aquellas que sean habitaciones compartidas (room_type==Shared room), y para 
aquellas viviendas compartidas debemos elegir aquellas con mayor puntuacion
"""

In [ ]:
#Forma 1
#Aplicamos el metodo query filtramos  por precio y tipo de habitacion
seleccion_diana=airbnb.query("price<=50/3 & room_type=='Shared room'")
seleccion_diana.head()

In [20]:
#Forma 2
seleccion_diana=airbnb[(airbnb.price<=50/3)&(airbnb.room_type=="Shared room")]
seleccion_diana.head()

,room_id,host_id,room_type,neighborhood,reviews,overall_satisfaction,accommodates,bedrooms,price
1010,1179457,5799522,Shared room,Santo António,42,4.0,16,1.0,10.0
2838,4010418,12771657,Shared room,Misericórdia,12,4.5,6,1.0,15.0
3562,5557699,28812904,Shared room,Santa Maria Maior,22,4.0,1,1.0,10.0
3597,5610245,29084261,Shared room,Santa Maria Maior,8,4.0,4,1.0,11.0
3738,5823046,29676067,Shared room,Misericórdia,35,4.5,12,1.0,15.0

In [24]:
#Ordenamos por precio de menor a mayor y por puntuacion de mayor a menor priorizando precio
seleccion_diana.sort_values(by=["price","overall_satisfaction"],ascending=[True,False]).head(10)

,room_id,host_id,room_type,neighborhood,reviews,overall_satisfaction,accommodates,bedrooms,price
1010,1179457,5799522,Shared room,Santo António,42,4.0,16,1.0,10.0
3562,5557699,28812904,Shared room,Santa Maria Maior,22,4.0,1,1.0,10.0
7584,13116032,72951043,Shared room,Arroios,1,0.0,8,1.0,10.0
13148,19314160,135270245,Shared room,Santa Clara,0,0.0,1,1.0,10.0
9065,14933182,91501272,Shared room,Santo António,5,5.0,8,1.0,11.0
4353,6728244,28812904,Shared room,Santa Maria Maior,8,4.5,1,1.0,11.0
5616,9317561,48360716,Shared room,Arroios,13,4.5,4,1.0,11.0
6640,11693356,28812904,Shared room,Santa Maria Maior,3,4.5,1,1.0,11.0
6641,11693442,28812904,Shared room,Santa Maria Maior,16,4.5,1,1.0,11.0
8908,14708916,91501272,Shared room,Santo António,18,4.5,4,1.0,11.0